package hospital_enterprise;

import java.awt.CardLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.Community;
import hospital_enterprise.Encounter;
import model.House;
import hospital_enterprise.Patient;
import model.Person;
import model.Sys;
import model.User;
import model.UserDirectory;
import hospital_enterprise.VitalSigns;
import ui.HomeScreen;
import utility.UtilityFunctions;

/**
 *
 * @author  Mihir Mehta / Hechen Gao
 */
public class Dashboard extends javax.swing.JPanel {
  
    private JPanel userProcessContainer;
    private Sys sys;
    Patient selectedPatient;
    private HomeScreen homeScreen;
    ImageIcon icon;
    private Encounter selectedEncounter;
    boolean abnormalitiesFlag = false;
    
    public Dashboard(JPanel userProcessContainer,Sys sys,HomeScreen homeScreen) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.sys = sys;
        this.homeScreen = homeScreen;
        setSize(1040, 544);
        makeUnEditable();
        populateTableInitially();
        clearFields();
        emptyCommunityComboBox();
        loadCommunity();
        loadCity();
        
    }
    
    public void makeUnEditable(){
    
        txtBP_LOW.setEnabled(false);
        txtBP_HIGH.setEnabled(false);
        txtHeartRate.setEnabled(false);
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
        
    }
    
     public void makeEditable(){
    
        txtBP_LOW.setEnabled(true);
        txtBP_HIGH.setEnabled(true);
        txtHeartRate.setEnabled(true);
    }
    
    public void loadCommunity(){
    
    
    for(City city: sys.getCityList()){
        
        for(Community com: city.getCommList()){
            cmbCommunitySearch.addItem(com.getCommName());
        }
        }   
    }
    
    public void loadCity(){
    
    
    for(City city: sys.getCityList()){
        
        cmbCity.addItem(city.getCitName());
    }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblUserpic = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtAddr = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tblEncounterHistory = new javax.swing.JScrollPane();
        tblEncHist = new javax.swing.JTable();
        lblEncounterHist = new javax.swing.JLabel();
        lblBP = new javax.swing.JLabel();
        lblHeartRate = new javax.swing.JLabel();
        txtBP_LOW = new javax.swing.JTextField();
        lblName2 = new javax.swing.JLabel();
        txtBP_HIGH = new javax.swing.JTextField();
        lblSlash = new javax.swing.JLabel();
        txtHeartRate = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lblNameData = new javax.swing.JLabel();
        lblDOBdata = new javax.swing.JLabel();
        lblAgeData = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnSearch = new javax.swing.JButton();
        lblBP1 = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        cmbCommunitySearch = new javax.swing.JComboBox<>();
        lblCity = new javax.swing.JLabel();
        cmbCity = new javax.swing.JComboBox<>();
        btnSowAbnormalities = new javax.swing.JButton();
        chkSearch = new javax.swing.JCheckBox();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(650, 600));

        jSeparator1.setForeground(new java.awt.Color(17, 125, 161));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jSeparator1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblUserpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/female_emp.jpg"))); // NOI18N

        lblName.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblName.setText("Name:");

        lblDOB.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblDOB.setText("DOB:");

        lblAge.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblAge.setText("Age:");

        txtAddr.setWheelScrollingEnabled(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        txtAddr.setViewportView(jTextArea1);

        tblEncHist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Pa. ID", "EncounterId", "Systolic BP", "Diastolic BP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEncHist.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblEncHistAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblEncounterHistory.setViewportView(tblEncHist);
        if (tblEncHist.getColumnModel().getColumnCount() > 0) {
            tblEncHist.getColumnModel().getColumn(0).setResizable(false);
            tblEncHist.getColumnModel().getColumn(1).setResizable(false);
            tblEncHist.getColumnModel().getColumn(2).setResizable(false);
            tblEncHist.getColumnModel().getColumn(3).setResizable(false);
            tblEncHist.getColumnModel().getColumn(4).setResizable(false);
        }

        lblEncounterHist.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lblEncounterHist.setText("Encounter Histories");

        lblBP.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblBP.setText("Blood pressure:");

        lblHeartRate.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblHeartRate.setText("Heart Rate:");

        txtBP_LOW.setText("90");

        lblName2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblName2.setText("/");

        txtBP_HIGH.setText("150");

        lblSlash.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblSlash.setText("mm Hg");

        txtHeartRate.setText("72");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblNameData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNameData.setText("Aniruddha Tambe");

        lblDOBdata.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDOBdata.setText("10/31/2021");

        lblAgeData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAgeData.setText("25");

        jSeparator2.setForeground(new java.awt.Color(17, 125, 161));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblBP1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblBP1.setText("Search by:");

        lblCommunity.setText("Community:");

        cmbCommunitySearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCity.setText("City:");

        cmbCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSowAbnormalities.setText("Abnormalities");
        btnSowAbnormalities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSowAbnormalitiesActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDOB)
                                .addComponent(lblAge)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameData)
                            .addComponent(lblAgeData)
                            .addComponent(lblDOBdata, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUserpic, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addComponent(txtAddr, 0, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblEncounterHist)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnSowAbnormalities))
                                            .addComponent(tblEncounterHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblBP1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(chkSearch))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblCommunity)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cmbCommunitySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnSearch)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblCity)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(29, 29, 29))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(162, 162, 162)
                                        .addComponent(lblBP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtBP_LOW, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(lblName2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBP_HIGH, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSlash))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(255, 255, 255)
                                        .addComponent(lblHeartRate)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addGap(186, 186, 186))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBP_LOW, txtHeartRate});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbCity, cmbCommunitySearch});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(272, 272, 272)
                                .addComponent(txtAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(194, 194, 194))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblEncounterHist, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSowAbnormalities))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tblEncounterHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblBP1)
                                        .addComponent(btnSearch)
                                        .addComponent(chkSearch))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblCommunity)
                                        .addComponent(cmbCommunitySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCity)
                                        .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(23, 23, 23)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblBP)
                                        .addComponent(txtBP_LOW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblName2)
                                        .addComponent(txtBP_HIGH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblSlash))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblHeartRate)
                                        .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnUpdate)
                                        .addComponent(btnView)
                                        .addComponent(btnDelete)))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(lblUserpic, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(lblNameData))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDOBdata)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAgeData))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDOB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAge)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        if(chkSearch.isSelected()){
            
            //Search logic
            populateTableBySearch();
            
        }else JOptionPane.showMessageDialog(this, "Search is OFF");
        
        
        
    }//GEN-LAST:event_btnSearchActionPerformed
    
    private void populateTableBySearch() {
        
        DefaultTableModel model = (DefaultTableModel) tblEncHist.getModel();
        
        //Delete empty rows
        model.setRowCount(0);
        
        //Filter patients by community & city
        ArrayList<Patient> filteredPatients = new ArrayList<Patient>();
        
        //Get community wise filtered patients
        filteredPatients.addAll(getFilteredPatientsTerritoryWise());
                
        //Create an array for search results
        ArrayList<Encounter> searchList = new ArrayList<>();
        
        //Populate the list with search appropriate values
        searchList.addAll(getFilteredEncountersList(filteredPatients));
        
        
        for(Encounter enc:searchList){
            
            if(abnormalitiesFlag){
                
                //Conditions for Low & high BP
                if(enc.getVital().getBloodPressure_LOW() < 120.5 && enc.getVital().getBloodPressure_LOW() > 114.5 && enc.getVital().getBloodPressure_HIGH() < 78.5 && enc.getVital().getBloodPressure_HIGH() > 75.5){
                    continue;
                }
            }
            
            Object[] row = new Object[5]; // Number of elements in the table - 6
            row[0] = enc;//.getName();
            row[1] = sys.getPatDir().getPatientFromEncounter(enc).getId()+"";
            row[2] = enc.getId();
            row[3] = enc.getVital().getBloodPressure_LOW();
            row[4] = enc.getVital().getBloodPressure_HIGH();
            
            model.addRow(row);
        }
        
        if(searchList.size() == 0){
            JOptionPane.showMessageDialog(this, "No results");
        }
        
        abnormalitiesFlag = false;
    }
    
    public ArrayList<Encounter> getFilteredEncountersList(ArrayList<Patient> filteredPatients){
    
        
        ArrayList<Encounter> filteredEncounter = new ArrayList<Encounter>();
        
        for(Patient pat:filteredPatients){
        
            //List with all patients data
            ArrayList<Encounter> allEncounter = pat.getEncounterHistory().getEncounterList();
            
            for(Encounter enc: allEncounter){
                
                filteredEncounter.add(enc);
                
                
                
            }
            
        }
        
        return filteredEncounter;
    }
    
    public ArrayList<Patient> getFilteredPatientsTerritoryWise(){
        
        ArrayList<Patient> patientList = new ArrayList<Patient>();
        
        //List with all patients data
        ArrayList<Patient> allPatient = sys.getPatDir().getPatientList();
        
        //Get applied filters
        
        String communitySearch = (String)cmbCommunitySearch.getSelectedItem();
        String citySearch = (String)cmbCity.getSelectedItem();
        
        //Start filtering
        int addPatientFilterPassCount = 0;
        int nullFilterPassCount = 0;
        
        for(Patient individualPat:allPatient){
            
           //Initial count to 0
           addPatientFilterPassCount = 0; 
           nullFilterPassCount = 0;
           
            //Filter for manufacturer
            if(!communitySearch.equals("-")){
                try{
                    House house = sys.findHouseInCity(individualPat.getPerson());
                    
                    if(house.getCommunity().equals(communitySearch)){
                        addPatientFilterPassCount += 1;
                    }
                }catch(Exception e){
                    
                }
            }else {
                nullFilterPassCount += 1;
            }
            
            
            //Filter for manufacturer
            if(!citySearch.equals("-")){
                try{
                    if(sys.findHouseInCity(individualPat.getPerson()).getCity().equals(citySearch)){
                        addPatientFilterPassCount += 1;
                    }
                }catch(Exception e){
                    
                }
            }else {
                nullFilterPassCount += 1;
            }
            
            
            if(addPatientFilterPassCount + nullFilterPassCount == 2){
                patientList.add(individualPat);
            }
        }
        
        return patientList;
    }
    
    public void emptyCommunityComboBox(){
    
        cmbCommunitySearch.removeAllItems();
        cmbCommunitySearch.addItem("-");
        cmbCity.removeAllItems();
        cmbCity.addItem("-");
    }
    
    
    
    public void populateTableForAllPatients(){
    
        for(Patient pat:sys.getPatDir().getPatientList()){
            populateTable(pat);
        }
        
    }
    
    private void populateTable(Patient selPatient) {
        
        DefaultTableModel model = (DefaultTableModel) tblEncHist.getModel();
        
        //Delete empty rows
        model.setRowCount(0);
        
        for(Encounter enc:selPatient.getEncounterHistory().getEncounterList()){
            
            Object[] row = new Object[5]; // Number of elements in the table - 6
            row[0] = enc;//.getName();
            row[1] = sys.getPatDir().getPatientFromEncounter(enc).getId()+"";
            row[2] = enc.getId();
            row[3] = enc.getVital().getBloodPressure_LOW();
            row[4] = enc.getVital().getBloodPressure_HIGH();
            
            model.addRow(row);
        }
        
        
        
    }
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        if(!validations()){
            return;
        }

        saveValues();

        JOptionPane.showMessageDialog(this, "Visit updated");

        populateTableInitially();
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblEncHist.getSelectedRow();
        
        if(selectedRow < 0){
            
            JOptionPane.showMessageDialog(this, "Please select a row");
        
        }else{
            
            //Make them uneditable
            makeUnEditable();
                    
            // Populate the fields
            //onlySelectedCar = selectedRow;
            
            //Handle Null pointer for empty values
            try{
                DefaultTableModel model = (DefaultTableModel) tblEncHist.getModel();
                Encounter selectEncounter = (Encounter) model.getValueAt(selectedRow, 0);
                selectedEncounter = selectEncounter;
                populateFields(selectEncounter);
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Select valid entry");
            }
            
            
        }
        //Populate personal details
        populatePersonalDetails(sys.getPatDir().getPatientFromEncounter(selectedEncounter));
    
    
        
        makeEditable();
        
        btnDelete.setEnabled(true);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnViewActionPerformed
    
    public void populatePersonalDetails(Patient patient){
      
                        
        Person person = patient.getPerson();
    
        UtilityFunctions utility = new UtilityFunctions();
        
        
        lblNameData.setText(person.getName());
        lblAgeData.setText(person.getAge()+"");
        lblDOBdata.setText(utility.covertDateToString(person.getDob()));

        //Display the image
        
        try{
        if(!person.getImagePath().equals("")){
            icon = new ImageIcon(person.getImagePath());
        }else {
            icon = new ImageIcon("user.png");
        }
        }catch(Exception e){
            icon = new ImageIcon("user.png");
        }
        
        lblUserpic.setIcon(icon);
        
        
        
    }
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        sys.getPatDir().getPatientFromEncounter(selectedEncounter).getEncounterHistory().getEncounterList().remove(selectedEncounter);
        
        JOptionPane.showMessageDialog(this, "Record deleted");
        
        populateTableInitially();
        
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSowAbnormalitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSowAbnormalitiesActionPerformed
        // TODO add your handling code here:
        
        abnormalitiesFlag = true;
        populateTableBySearch();
    }//GEN-LAST:event_btnSowAbnormalitiesActionPerformed

    private void jSeparator1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jSeparator1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jSeparator1AncestorAdded

    private void tblEncHistAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblEncHistAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEncHistAncestorAdded

    private void populateFields(Encounter selectedEncounter) {
        
            
        txtBP_LOW.setText(selectedEncounter.getVital().getBloodPressure_LOW()+"");
        txtBP_HIGH.setText(selectedEncounter.getVital().getBloodPressure_HIGH()+"");
        txtHeartRate.setText(selectedEncounter.getVital().getHeartRate()+"");
        
    }
    
    public void populateDate(){
        
        UtilityFunctions util = new UtilityFunctions();
        
        //lblTodaysData.setText(util.covertDateToString(LocalDate.now()));
        
    }    
    public void saveValues(){
        
        UtilityFunctions util = new UtilityFunctions();
        
        double BP_LOW = util.convertToDouble(txtBP_LOW.getText());
        double BP_HIGH = util.convertToDouble(txtBP_HIGH.getText());
        double HR = util.convertToDouble(txtHeartRate.getText());
        
        selectedEncounter.getVital().setBloodPressure_HIGH(BP_HIGH);
        selectedEncounter.getVital().setBloodPressure_LOW(BP_LOW);
        selectedEncounter.getVital().setHeartRate(HR);
        
    }
    public boolean validations(){
        
       UtilityFunctions utility = new UtilityFunctions();
        
        //Field validations
        boolean valFlag = true;
        int misCounter = 0;
        int temp = 0;
        
        //Error Message
        String errorMessage = "";
        
        //1. BP Low Number ***************************************************************************
        
        // TC.1 - No Null value
        temp = misCounter;
        misCounter = misCounter + utility.runValidation(".+",txtBP_LOW.getText());
        
        //Add message
        if(temp != misCounter){
            errorMessage = errorMessage + "Missing value in BP-Low field"+"\n";
        }
        
        //TC.2 - No special characters
        temp = misCounter;
        misCounter = misCounter + utility.runValidation("^([^!@#$%^&*()]*)$",txtBP_LOW.getText());
        
        //Add message
        if(temp != misCounter){
            errorMessage = errorMessage + "Remove special characters in BP-Low field"+"\n";
        }
        
        //TC.3 - Only numbers
        temp = misCounter;
        misCounter = misCounter + utility.runValidation("^[0-9]*\\.?[0-9]*$",txtBP_LOW.getText());
        
        //Add message
        if(temp != misCounter){
            errorMessage = errorMessage + "Please enter numbers in city field"+"\n";
        }
        
       //2. BP High Number ***************************************************************************
       
       // TC.1 - No Null value
        temp = misCounter;
        misCounter = misCounter + utility.runValidation(".+",txtBP_HIGH.getText());
        
        //Add message
        if(temp != misCounter){
            errorMessage = errorMessage + "Missing value in BP-Low field"+"\n";
        }
        
        //TC.2 - No special characters
        temp = misCounter;
        misCounter = misCounter + utility.runValidation("^([^!@#$%^&*()]*)$",txtBP_HIGH.getText());
        
        //Add message
        if(temp != misCounter){
            errorMessage = errorMessage + "Remove special characters in BP-Low field"+"\n";
        }
        
        //TC.3 - Only numbers
        temp = misCounter;
        misCounter = misCounter + utility.runValidation("^[0-9]*\\.?[0-9]*$",txtBP_HIGH.getText());
        
        //Add message
        if(temp != misCounter){
            errorMessage = errorMessage + "Please enter numbers in city field"+"\n";
        }
        
        
       //3. Heart rate ***************************************************************************
       // TC.1 - No Null value
        temp = misCounter;
        misCounter = misCounter + utility.runValidation(".+",txtHeartRate.getText());
        
        //Add message
        if(temp != misCounter){
            errorMessage = errorMessage + "Missing value in BP-Low field"+"\n";
        }
        
        //TC.2 - No special characters
        temp = misCounter;
        misCounter = misCounter + utility.runValidation("^([^!@#$%^&*()]*)$",txtHeartRate.getText());
        
        //Add message
        if(temp != misCounter){
            errorMessage = errorMessage + "Remove special characters in BP-Low field"+"\n";
        }
        
        //TC.3 - Only numbers
        temp = misCounter;
        misCounter = misCounter + utility.runValidation("^[0-9]+$",txtHeartRate.getText());
        
        //Add message
        if(temp != misCounter){
            errorMessage = errorMessage + "Please enter numbers in city field"+"\n";
        }
       
       
       // ********************************************************************************************
        // Check validations
        if(misCounter > 0){
           JOptionPane.showMessageDialog(this, errorMessage);
           valFlag = false;
        }
        // ********************************************************************************************
        
        
        return valFlag;
        
    }

    
    public void populateDetails(Patient selectedPatient){
    
        //Patient section
        populatePersonSection(selectedPatient);
        
        //Encounter section
        
        
        
    }
    
     public void clearFields(){
        
        lblNameData.setText("");
        lblAgeData.setText("");
        lblDOBdata.setText("");
        txtBP_LOW.setText("");
        txtBP_HIGH.setText("");
        txtHeartRate.setText("");
        
        //Display the image
        icon = new ImageIcon("C://Users//user//Documents//NetBeansProjects//Lab_3_Skeleton//src//res//AED_ASS_4_user.png");
        //icon = utility.scaleImage(icon, 320, 240);
        
        lblUserpic.setIcon(icon);
        
    }
    
    public void populatePersonSection(Patient selectedPatient){
        
        Person person = selectedPatient.getPerson();
        UtilityFunctions utility = new UtilityFunctions();
        
        lblNameData.setText(person.getName());
        lblAgeData.setText(person.getAge()+"");
        lblDOBdata.setText(utility.covertDateToString(person.getDob()));

        //Display the image
        icon = new ImageIcon(person.getImagePath());
        //icon = utility.scaleImage(icon, 320, 240);
        
        lblUserpic.setIcon(icon);
    }
    
    
    private void populateTableInitially() {
        
        DefaultTableModel model = (DefaultTableModel) tblEncHist.getModel();
        
        //Delete empty rows
        model.setRowCount(0);
        
        ArrayList<Encounter> allEncounter = new ArrayList<Encounter>();
        
        for(Patient allPatient:sys.getPatDir().getPatientList()){
            
            for(Encounter enc:allPatient.getEncounterHistory().getEncounterList()){

                Object[] row = new Object[5]; // Number of elements in the table - 6
                row[0] = enc;//.getName();
                row[1] = sys.getPatDir().getPatientFromEncounter(enc).getId()+"";
                row[2] = enc.getId();
                row[3] = enc.getVital().getBloodPressure_LOW();
                row[4] = enc.getVital().getBloodPressure_HIGH();

                model.addRow(row);
            }
        }
        
        
        
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSowAbnormalities;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JCheckBox chkSearch;
    private javax.swing.JComboBox<String> cmbCity;
    private javax.swing.JComboBox<String> cmbCommunitySearch;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAgeData;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblBP1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOBdata;
    private javax.swing.JLabel lblEncounterHist;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblNameData;
    private javax.swing.JLabel lblSlash;
    private javax.swing.JLabel lblUserpic;
    private javax.swing.JTable tblEncHist;
    private javax.swing.JScrollPane tblEncounterHistory;
    private javax.swing.JScrollPane txtAddr;
    private javax.swing.JTextField txtBP_HIGH;
    private javax.swing.JTextField txtBP_LOW;
    private javax.swing.JTextField txtHeartRate;
    // End of variables declaration//GEN-END:variables

    
}
