/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NewsModel;
import NewsModel.NewsHistory;
import NewsModel.NewspaperHistory;
import NewsModel.AuthorHistory;
import NewsModel.PublicationHistory;
import NewsModel.ReporterHistory;

/**
 *
 * @author Sal <your.name at your.org>
 */
public class NewsMainJPanel extends javax.swing.JPanel {
    NewsHistory news;
    NewspaperHistory newspaper;
    AuthorHistory author;
    PublicationHistory publication;
    ReporterHistory reporter;
    TelevisionHistory tv;
    /**
     * Creates new form NewsMainJPanel
     */
    public NewsMainJPanel() {
        initComponents();
        this.news = new NewsHistory();
        this.newspaper = new NewspaperHistory();
        this.author = new AuthorHistory();
        this.publication = new PublicationHistory();
        this.reporter = new ReporterHistory();
        this.tv = new TelevisionHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJSplitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        newsBtn = new javax.swing.JButton();
        newspaperBtn = new javax.swing.JButton();
        televisionBtn = new javax.swing.JButton();
        publicationBtn = new javax.swing.JButton();
        authorBtn = new javax.swing.JButton();
        reporterBtn = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        controlPanel.setBackground(new java.awt.Color(137, 152, 159));

        newsBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        newsBtn.setText("NEWS");
        newsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsBtnActionPerformed(evt);
            }
        });

        newspaperBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        newspaperBtn.setText("NEWSPAPER");
        newspaperBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newspaperBtnActionPerformed(evt);
            }
        });

        televisionBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        televisionBtn.setText("TELEVISION");
        televisionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                televisionBtnActionPerformed(evt);
            }
        });

        publicationBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        publicationBtn.setText("PUBLICATION");
        publicationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicationBtnActionPerformed(evt);
            }
        });

        authorBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        authorBtn.setText("AUTHOR");
        authorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorBtnActionPerformed(evt);
            }
        });

        reporterBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        reporterBtn.setText("REPORTER");
        reporterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporterBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(authorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newspaperBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(televisionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publicationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reporterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(authorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newspaperBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(televisionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(publicationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reporterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        mainJSplitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(137, 152, 159));

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        mainJSplitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJSplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsBtnActionPerformed
        // TODO add your handling code here:
        NewsViewJPanel newsPanel = new NewsViewJPanel(news);
        mainJSplitPane.setRightComponent(newsPanel);
    }//GEN-LAST:event_newsBtnActionPerformed

    private void newspaperBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newspaperBtnActionPerformed
        // TODO add your handling code here:
        NewspaperViewJPanel newspaperPanel = new NewspaperViewJPanel(newspaper);
        mainJSplitPane.setRightComponent(newspaperPanel);
    }//GEN-LAST:event_newspaperBtnActionPerformed

    private void televisionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_televisionBtnActionPerformed
        // TODO add your handling code here:
        TelevisionViewJPanel tvPanel = new TelevisionViewJPanel(tv);
        mainJSplitPane.setRightComponent(tvPanel);
    }//GEN-LAST:event_televisionBtnActionPerformed

    private void publicationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicationBtnActionPerformed
        // TODO add your handling code here:
        PublicationViewJPanel publicationPanel = new PublicationViewJPanel(publication);
        mainJSplitPane.setRightComponent(publicationPanel);
    }//GEN-LAST:event_publicationBtnActionPerformed

    private void authorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorBtnActionPerformed
        // TODO add your handling code here:
        AuthorViewJPanel authPanel = new AuthorViewJPanel(author);
        mainJSplitPane.setRightComponent(authPanel);
    }//GEN-LAST:event_authorBtnActionPerformed

    private void reporterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporterBtnActionPerformed
        // TODO add your handling code here:
        ReporterViewJPanel reporterPanel = new ReporterViewJPanel(reporter);
        mainJSplitPane.setRightComponent(reporterPanel);
    }//GEN-LAST:event_reporterBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authorBtn;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane mainJSplitPane;
    private javax.swing.JButton newsBtn;
    private javax.swing.JButton newspaperBtn;
    private javax.swing.JButton publicationBtn;
    private javax.swing.JButton reporterBtn;
    private javax.swing.JButton televisionBtn;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
