/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NewsModel;
import javax.swing.table.DefaultTableModel;
import NewsModel.Author;
import NewsModel.AuthorHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author Sal <your.name at your.org>
 */
public class ReadAuthorJPanel extends javax.swing.JPanel {
    AuthorHistory authHistory;

    /**
     * Creates new form ReadAuthorJPanel
     */
    public ReadAuthorJPanel(AuthorHistory authHistory) {
        initComponents();
        this.authHistory  = authHistory;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewDocNameLabel = new javax.swing.JLabel();
        NewDocIDLabel = new javax.swing.JLabel();
        NewDocHospNameLabel = new javax.swing.JLabel();
        NewDocHospIDLabel = new javax.swing.JLabel();
        NewDocPhnLabel = new javax.swing.JLabel();
        NewAuthIdTxt = new javax.swing.JTextField();
        NewAuthNameTxt = new javax.swing.JTextField();
        NewAuthAgeTxt = new javax.swing.JTextField();
        HeadingLabel = new javax.swing.JLabel();
        NewAuthGenderTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AuthDirectoryTable = new javax.swing.JTable();
        NewAuthYoeTxt = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        NewDocPhnTxt1 = new javax.swing.JTextField();
        NewDocPhnLabel1 = new javax.swing.JLabel();
        NewAuthDojTxt = new javax.swing.JTextField();
        NewDocPhnLabel2 = new javax.swing.JLabel();

        NewDocNameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        NewDocNameLabel.setText("NAME ");

        NewDocIDLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        NewDocIDLabel.setText(" ID");

        NewDocHospNameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        NewDocHospNameLabel.setText("YEARS OF EXPERIENCE");

        NewDocHospIDLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        NewDocHospIDLabel.setText("AGE");

        NewDocPhnLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        NewDocPhnLabel.setText("GENDER");

        NewAuthNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAuthNameTxtActionPerformed(evt);
            }
        });

        NewAuthAgeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAuthAgeTxtActionPerformed(evt);
            }
        });

        HeadingLabel.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        HeadingLabel.setText("AUTHOR DIRECTORY");

        NewAuthGenderTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAuthGenderTxtActionPerformed(evt);
            }
        });

        AuthDirectoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "AUTHOR ID", "AUTHOR NAME", "AUTHOR AGE", "AUTHOR YOE", "AUTHOR GENDER", "AUTHOR DOJ"
            }
        ));
        jScrollPane1.setViewportView(AuthDirectoryTable);

        updateBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        viewBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        viewBtn.setText("VIEW");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        NewDocPhnTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewDocPhnTxt1ActionPerformed(evt);
            }
        });

        NewDocPhnLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        NewDocPhnLabel1.setText("DATE OF JOINING");

        NewAuthDojTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAuthDojTxtActionPerformed(evt);
            }
        });

        NewDocPhnLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        NewDocPhnLabel2.setText("DATE OF JOINING");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NewDocIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NewDocPhnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NewDocNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NewAuthNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NewAuthGenderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NewAuthIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NewDocPhnLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(NewAuthDojTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(NewDocPhnLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(NewDocPhnTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(NewDocHospIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(NewDocHospNameLabel))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NewAuthAgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NewAuthYoeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(HeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(HeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewAuthIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewDocIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NewDocNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewAuthNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NewDocHospIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewAuthAgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NewDocHospNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewAuthYoeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NewDocPhnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewAuthGenderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewDocPhnLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewAuthDojTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(516, 516, 516)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewDocPhnLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewDocPhnTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NewAuthNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAuthNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewAuthNameTxtActionPerformed

    private void NewAuthAgeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAuthAgeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewAuthAgeTxtActionPerformed

    private void NewAuthGenderTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAuthGenderTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewAuthGenderTxtActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed

//        boolean isValid = Validation();
//        if (isValid) {
            int selectedRowIndex = AuthDirectoryTable.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a row to update");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) AuthDirectoryTable.getModel();
            Author selectedAuthor = (Author) model.getValueAt(selectedRowIndex, 0);
            String authId = NewAuthIdTxt.getText();
            String authName = NewAuthNameTxt.getText();
            int authAge = Integer.parseInt(NewAuthAgeTxt.getText());
            int authYoe = Integer.parseInt(NewAuthYoeTxt.getText());
            String authGender = NewAuthGenderTxt.getText();
            String authDoj = NewAuthDojTxt.getText();

            JOptionPane.showMessageDialog(this, "Doctor Information Updated");
            //history.deleteEmployee(selectedEmployee);
            selectedAuthor.setAuthorId(authId);
            selectedAuthor.setAuthorName(authName);
            selectedAuthor.setAuthorAge(authAge);
            selectedAuthor.setAuthorGender(authGender);
            selectedAuthor.setAuthorDateOfJoining(authDoj);
            selectedAuthor.setAuthorYearsOfExperience(authYoe);
            

            populateTable();

            NewAuthIdTxt.setText("");
            NewAuthNameTxt.setText("");
            NewAuthAgeTxt.setText("");
            NewAuthYoeTxt.setText("");
            NewAuthGenderTxt.setText("");
            NewAuthDojTxt.setText("");
        //}

    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = AuthDirectoryTable.getSelectedRow();

        if(selectedRowIndex <0){
            JOptionPane.showMessageDialog(this, "Please enter the row you want to delete");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) AuthDirectoryTable.getModel();
        Author author = (Author) model.getValueAt(selectedRowIndex,0);

        authHistory.deleteAuthor(author);

        JOptionPane.showMessageDialog(this, "Requested Record is Deleted");
        populateTable();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = AuthDirectoryTable.getSelectedRow();
        if(selectedRowIndex <0){
            JOptionPane.showMessageDialog(this, "Please enter the row you want to view");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) AuthDirectoryTable.getModel();
        Author author = (Author) model.getValueAt(selectedRowIndex,0);

        NewAuthIdTxt.setText(String.valueOf(author.getAuthorId()));
        NewAuthNameTxt.setText(String.valueOf(author.getAuthorName()));
        NewAuthAgeTxt.setText(String.valueOf(author.getAuthorAge()));
        NewAuthYoeTxt.setText(String.valueOf(author.getAuthorYearsOfExperience()));
        NewAuthGenderTxt.setText(String.valueOf(author.getAuthorGender()));
        NewAuthDojTxt.setText(String.valueOf(author.getAuthorDateOfJoining()));
    }//GEN-LAST:event_viewBtnActionPerformed

    private void NewDocPhnTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewDocPhnTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewDocPhnTxt1ActionPerformed

    private void NewAuthDojTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAuthDojTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewAuthDojTxtActionPerformed
    
    private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) AuthDirectoryTable.getModel();
        model.setRowCount(0);

        for (Author auth : authHistory.getAuthData()) {

            Object[] row = new Object[7];
            row[0] = auth;
            row[1] = auth.getAuthorId();
            row[2] = auth.getAuthorName();
            row[3] = auth.getAuthorGender();
            row[4] = auth.getAuthorAge();
            row[5] = auth.getAuthorDateOfJoining();
            row[6] = auth.getAuthorYearsOfExperience();

            model.addRow(row);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AuthDirectoryTable;
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JTextField NewAuthAgeTxt;
    private javax.swing.JTextField NewAuthDojTxt;
    private javax.swing.JTextField NewAuthGenderTxt;
    private javax.swing.JTextField NewAuthIdTxt;
    private javax.swing.JTextField NewAuthNameTxt;
    private javax.swing.JTextField NewAuthYoeTxt;
    private javax.swing.JLabel NewDocHospIDLabel;
    private javax.swing.JLabel NewDocHospNameLabel;
    private javax.swing.JLabel NewDocIDLabel;
    private javax.swing.JLabel NewDocNameLabel;
    private javax.swing.JLabel NewDocPhnLabel;
    private javax.swing.JLabel NewDocPhnLabel1;
    private javax.swing.JLabel NewDocPhnLabel2;
    private javax.swing.JTextField NewDocPhnTxt1;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
