/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package crime_branch_enterprise.model;


import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.JTextFieldLimit;
import model.Sys;
import model.User;
import model.UserDirectory;
import ui.HomeScreen;
import utility.RandomString;
import utility.Validation;
//import utility

/**
 *
 * @author hindupurv
 */
public class CreateNewCaseRegisterationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewCaseRegisterationJPanel
     */
    private JPanel newCaseRegisterPanel;
    private Sys sys;
    private HomeScreen homeScreen;
    
    DatabaseConnection_CaseDetails dbConnCaseDetails;
    DatabaseConnection_adminUser dbConnAdmin;
    
    NewCaseRegister newCaseRegister;
    OfficerDirectory officerDir;
    
    FIRDirectory fIRDirectory;
    NewCaseRegisterDirectory newCaseRegisterDir;
    UserDirectory userDir;
    Validation validation;
    
    public CreateNewCaseRegisterationJPanel(NewCaseRegisterDirectory newCaseRegisterDir, OfficerDirectory officerDir)
    {
        initComponents();
        this.newCaseRegisterDir = newCaseRegisterDir;
        this.officerDir = officerDir;
        
        //add officerName
        for(Officer officerRecord : officerDir.officerList)
        {
            SelectOfficerDropdown.addItem(officerRecord.getOfficerName());
        }
    }
    
    public CreateNewCaseRegisterationJPanel(JPanel newCaseRegisterPanel,Sys sys,HomeScreen homeScreen) {
        initComponents();
        
        this.newCaseRegisterPanel = newCaseRegisterPanel;
        this.sys = sys;
        this.homeScreen = homeScreen;
        setSize(1040, 544);
        
        //limitations added
        PhoneNumberTextField.setDocument(new JTextFieldLimit(10));
        EmailIdTextField.setDocument(new JTextFieldLimit(50));
        
        dbConnCaseDetails = new DatabaseConnection_CaseDetails();
        fIRDirectory = new FIRDirectory();
        userDir = new UserDirectory();
        validation = new Validation();
        
        newCaseRegister = new NewCaseRegister();
        
        
    }
    
    public void clearFields(){
        
        //add fields so they can be cleared
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        DateOfReportDateChooser = new com.toedter.calendar.JDateChooser();
        DateOfReportLabel = new javax.swing.JLabel();
        PhoneNumberTextField = new javax.swing.JTextField();
        SelectFIRNumberLabel = new javax.swing.JLabel();
        SelectOfficerDropdown = new javax.swing.JComboBox<>();
        SubmitDetailsButton = new java.awt.Button();
        EmailIdLabel = new javax.swing.JLabel();
        EmailIdTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 102, 153));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Register your case below by adding all the details.........");

        DescriptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DescriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        DescriptionLabel.setText("Phone Number:");

        DateOfReportDateChooser.setDateFormatString("YYYY-MM-dd");

        DateOfReportLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DateOfReportLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateOfReportLabel.setText("Date Of Report:");

        PhoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberTextFieldActionPerformed(evt);
            }
        });
        PhoneNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PhoneNumberTextFieldKeyPressed(evt);
            }
        });

        SelectFIRNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SelectFIRNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        SelectFIRNumberLabel.setText("Select Officer:");

        SubmitDetailsButton.setLabel("Submit Details");
        SubmitDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitDetailsButtonActionPerformed(evt);
            }
        });

        EmailIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EmailIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailIdLabel.setText("Email Id:");

        EmailIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailIdTextFieldActionPerformed(evt);
            }
        });
        EmailIdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmailIdTextFieldKeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SelectFIRNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SelectOfficerDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(EmailIdLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(EmailIdTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(DateOfReportLabel)
                                        .addComponent(DescriptionLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DateOfReportDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(303, 303, 303)
                                .addComponent(SubmitDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateOfReportLabel)
                            .addComponent(DateOfReportDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DescriptionLabel)
                            .addComponent(PhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailIdLabel)
                            .addComponent(EmailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectFIRNumberLabel)
                            .addComponent(SelectOfficerDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(SubmitDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PhoneNumberTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhoneNumberTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberTextFieldKeyPressed

    private void PhoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberTextFieldActionPerformed

    private void SubmitDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitDetailsButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            boolean flagValidate = true;
            int phoneNum = 0;
            String officerName = "";
            java.sql.Date sqlDate = null;
            java.util.Date utilDate = null;
            String inputDate = "";
            
            String emailId = EmailIdLabel.getText();
            if(!validation.emailTextFieldValidation(emailId))
            {
                JOptionPane.showMessageDialog(this, "valid Email Example a@b.com ");
                flagValidate = false;
            }
            
            try
            {
                phoneNum = Integer.parseInt(PhoneNumberTextField.getText());
                if(!validation.PhoneNumberTextFieldValidationIsNotNull(String.valueOf(phoneNum)))
                {
                    JOptionPane.showMessageDialog(this, "Enter valid Phone Number");
                    flagValidate = false;
                }
            }
            catch(NumberFormatException ex)
            { 
                JOptionPane.showMessageDialog(this, "Enter valid Phone Number ");
                flagValidate = false;
            }
           
            try
            {
                officerName = SelectOfficerDropdown.getSelectedItem().toString();
            }
            catch(NullPointerException e)
            {
                JOptionPane.showMessageDialog(this, "Select Officer");
                flagValidate = false;
            }
            
            try
            {
                utilDate = DateOfReportDateChooser.getDate();
                inputDate = DateOfReportDateChooser.getDate().toString();
                if(validation.futureDateValidation(inputDate) < 0)
                {
                    flagValidate = false;
                }
                else
                {
                    sqlDate =new java.sql.Date(utilDate.getDate());
                }
            }
            catch(NullPointerException e)
            {
                JOptionPane.showMessageDialog(this, "Select Date");
                flagValidate = false;
            }
            
            if(flagValidate)
            {
                newCaseRegister.setEmailId(emailId);
                newCaseRegister.setPhoneNum(String.valueOf(phoneNum));
                newCaseRegister.setDateOfReport(sqlDate);
                newCaseRegister.setOfficerName(officerName);

                //added to DB
                dbConnCaseDetails.addCaseDataToDB(newCaseRegister);

                //added to arraylist
                newCaseRegisterDir.addNewCaseDataInList(newCaseRegister);

                JOptionPane.showMessageDialog(this, "Case Registered under "+officerName+" officer");

                //victim username, password generate

                RandomString randomString = new RandomString();
                String username = randomString.getAlphaNumericString(5);
                String password = randomString.getAlphaNumericString(5);

                String jTable1Data[] = {username,password};
                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                tableModel.addRow(jTable1Data);

                //store this string in db 
                User user = new User();
                user.getUsername();
                user.getPassword();
                user.getRole();

                //added to arraylist
                userDir.addUser(user);

                //added to DB
                dbConnAdmin.addUserDataToDatabase(user);
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SubmitDetailsButtonActionPerformed

    private void EmailIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailIdTextFieldActionPerformed

    private void EmailIdTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailIdTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailIdTextFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateOfReportDateChooser;
    private javax.swing.JLabel DateOfReportLabel;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JLabel EmailIdLabel;
    private javax.swing.JTextField EmailIdTextField;
    private javax.swing.JTextField PhoneNumberTextField;
    private javax.swing.JLabel SelectFIRNumberLabel;
    private javax.swing.JComboBox<String> SelectOfficerDropdown;
    private java.awt.Button SubmitDetailsButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
