/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package crime_branch_enterprise.model;

import crime_branch_enterprise.model.SmsSender;
import java.sql.PreparedStatement;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.JTextFieldLimit;
import model.Sys;
import ui.HomeScreen;
import utility.Validation;



/**
 *
 * @author hindupurv
 */
public class CreateNewFIRRegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewFIRRegisterJPanel
     */
    private JPanel newFIRRegisterPanel;
    private Sys sys;
    private HomeScreen homeScreen;
    DatabaseConnection_FirDetails dbConnFIRDetails;
    PreparedStatement stmt;
    FIRDirectory fIRDirectory;
    Validation validation;
    
    public static boolean createFir = false;
    public static String valueAccVic = "";

    public CreateNewFIRRegisterJPanel(FIRDirectory fIRDirectory) {
        this.fIRDirectory = fIRDirectory;
        initComponents();

        validation = new Validation();

        dbConnFIRDetails = new DatabaseConnection_FirDetails();
        DescriptionTextField.setDocument(new JTextFieldLimit(250));
        FirstNameTextField.setDocument(new JTextFieldLimit(10));
        LastNameTextField.setDocument(new JTextFieldLimit(10));
        AddressTextField.setDocument(new JTextFieldLimit(10));
        PhoneNumberTextField.setDocument(new JTextFieldLimit(10));
        EmailIdTextField.setDocument(new JTextFieldLimit(50));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        PhoneNumberLabel = new javax.swing.JLabel();
        DateOfOffenceFIRDateChooser = new com.toedter.calendar.JDateChooser();
        DateOfOffenceLabel = new javax.swing.JLabel();
        DescriptionTextField = new javax.swing.JTextField();
        SelectPoliceStationLabel = new javax.swing.JLabel();
        SelectPoliceStation = new javax.swing.JComboBox<>();
        DateOfOffenceLabel2 = new javax.swing.JLabel();
        SubmitDetailsButton = new java.awt.Button();
        SelectAccusedOrVictim = new javax.swing.JComboBox<>();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        EmailIdLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        AddressTextField = new javax.swing.JTextField();
        EmailIdTextField = new javax.swing.JTextField();
        PhoneNumberTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        DescriptionLabel1 = new javax.swing.JLabel();
        dateFld = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 0, 0));

        titleLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Register your FIR :");

        PhoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PhoneNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNumberLabel.setText("Phone Number:");

        DateOfOffenceFIRDateChooser.setDateFormatString("MMM d, y");
        DateOfOffenceFIRDateChooser.setMinSelectableDate(new java.util.Date(-62135747930000L));

        DateOfOffenceLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DateOfOffenceLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateOfOffenceLabel.setText("DateOfOffence:");

        DescriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionTextFieldActionPerformed(evt);
            }
        });
        DescriptionTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DescriptionTextFieldKeyPressed(evt);
            }
        });

        SelectPoliceStationLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SelectPoliceStationLabel.setForeground(new java.awt.Color(255, 255, 255));
        SelectPoliceStationLabel.setText("Select Police Station:");

        SelectPoliceStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cambridge", "Jamican Plain", "Roxbury", "Downtown" }));
        SelectPoliceStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectPoliceStationActionPerformed(evt);
            }
        });

        DateOfOffenceLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DateOfOffenceLabel2.setForeground(new java.awt.Color(255, 255, 255));
        DateOfOffenceLabel2.setText("Accused OR Victim:");

        SubmitDetailsButton.setBackground(new java.awt.Color(102, 0, 0));
        SubmitDetailsButton.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        SubmitDetailsButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitDetailsButton.setLabel("Submit Details");
        SubmitDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitDetailsButtonActionPerformed(evt);
            }
        });

        SelectAccusedOrVictim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accused", "Victim" }));
        SelectAccusedOrVictim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectAccusedOrVictimActionPerformed(evt);
            }
        });

        FirstNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FirstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        FirstNameLabel.setText("FirstName:");

        LastNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        LastNameLabel.setText("LastName:");

        EmailIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EmailIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailIdLabel.setText("EmailId:");

        AddressLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddressLabel.setForeground(new java.awt.Color(255, 255, 255));
        AddressLabel.setText("Address: ");

        DescriptionLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DescriptionLabel1.setForeground(new java.awt.Color(255, 255, 255));
        DescriptionLabel1.setText("Description (in 250 words):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(FirstNameLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(DateOfOffenceLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(DateOfOffenceFIRDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dateFld))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LastNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DescriptionLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SelectPoliceStationLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SelectPoliceStation, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(DescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(546, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddressLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DateOfOffenceLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PhoneNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(SubmitDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EmailIdLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(EmailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(379, 379, 379)
                                        .addComponent(SelectAccusedOrVictim, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titleLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameLabel)
                            .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DescriptionLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DateOfOffenceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DateOfOffenceFIRDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(dateFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LastNameLabel)
                                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SelectPoliceStationLabel)
                                    .addComponent(SelectPoliceStation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressLabel)
                            .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateOfOffenceLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelectAccusedOrVictim, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailIdLabel)
                            .addComponent(EmailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PhoneNumberLabel)
                        .addComponent(PhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SubmitDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(409, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DescriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionTextFieldActionPerformed

    private void DescriptionTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DescriptionTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionTextFieldKeyPressed

    private void SubmitDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitDetailsButtonActionPerformed
        boolean textSent =SmsSender.sendSms(PhoneNumberTextField.getText(), "Your FIR is lodged. It is being reviewd by the Officer. We'll get back to you soon");
        boolean flagValidate = true;
        String descr = DescriptionTextField.getText();
        String firstName = FirstNameTextField.getText();
        String lastName = LastNameTextField.getText();
        String emailId = EmailIdTextField.getText();
        
        String address = AddressTextField.getText();
        String valuePoliceStn = SelectPoliceStation.getSelectedItem().toString();
        String valueAccVic = SelectAccusedOrVictim.getSelectedItem().toString();
        String phoneNumber = PhoneNumberTextField.getText();
        

        if (!validation.StringTextFieldValidationIsNotNull(firstName)) {
            JOptionPane.showMessageDialog(this, "Enter valid first name");
            flagValidate = false;
        }

        if (!validation.StringTextFieldValidationIsNotNull(lastName)) {
            JOptionPane.showMessageDialog(this, "Enter valid last name");
            flagValidate = false;
        }

        if (!validation.emailTextFieldValidation(emailId)) {
            JOptionPane.showMessageDialog(this, "valid Email Example a@b.com ");
            flagValidate = false;
        }

        if (!validation.PhoneNumberTextFieldValidationIsNotNull(phoneNumber)) {
            JOptionPane.showMessageDialog(this, "Enter valid Phone Number");
            flagValidate = false;
        }


        if (descr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Add Description");
            flagValidate = false;
        }
        
        if(flagValidate)
        {
            int year = DateOfOffenceFIRDateChooser.getCalendar().get(Calendar.YEAR);
            int month = DateOfOffenceFIRDateChooser.getCalendar().get(Calendar.MONTH);
            int date = DateOfOffenceFIRDateChooser.getCalendar().get(Calendar.DAY_OF_MONTH);

            String resultDate = year+"-"+(month+1)+"-"+date;
            dateFld.setText(resultDate);
            
            fIRDirectory.firList.add(new FIR(resultDate, descr, valuePoliceStn, valueAccVic, firstName, lastName, emailId, phoneNumber, address));

            //add to database firDetails
            FIR fir = new FIR();
            fir.setDateOfOffence(resultDate);
            fir.setDescr(descr);
            fir.setFirstname(firstName);
            fir.setLastname(lastName);
            fir.setEmailId(emailId);
            fir.setPhoneNum(phoneNumber);
            fir.setAddress(address);
            fir.setPoliceStationLoc(valuePoliceStn);
            fir.setAccorvic(valueAccVic);

            //fir add to arraylist
            fIRDirectory.addNewFIR(fir);
            
//            DateOfOffenceFIRDateChooser.setDateFormatString;
            
            //add data to db
            dbConnFIRDetails.addFIRDataToDB(fir);
            
            JOptionPane.showMessageDialog(this, "FIR Created!");
            
            createFir = true;
            
            this.valueAccVic = valueAccVic;
        }

    }//GEN-LAST:event_SubmitDetailsButtonActionPerformed

    private void SelectPoliceStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectPoliceStationActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SelectPoliceStationActionPerformed

    private void SelectAccusedOrVictimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectAccusedOrVictimActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SelectAccusedOrVictimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressTextField;
    private com.toedter.calendar.JDateChooser DateOfOffenceFIRDateChooser;
    private javax.swing.JLabel DateOfOffenceLabel;
    private javax.swing.JLabel DateOfOffenceLabel2;
    private javax.swing.JLabel DescriptionLabel1;
    private javax.swing.JTextField DescriptionTextField;
    private javax.swing.JLabel EmailIdLabel;
    private javax.swing.JTextField EmailIdTextField;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JTextField PhoneNumberTextField;
    private javax.swing.JComboBox<String> SelectAccusedOrVictim;
    private javax.swing.JComboBox<String> SelectPoliceStation;
    private javax.swing.JLabel SelectPoliceStationLabel;
    private java.awt.Button SubmitDetailsButton;
    private javax.swing.JTextField dateFld;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
