/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package crime_branch_enterprise.model;


import java.sql.PreparedStatement;
import javax.swing.JPanel;
import model.JTextFieldLimit;
import model.Sys;
import ui.HomeScreen;
//import utility

/**
 *
 * @author hindupurv
 */
public class NewCaseRegisterationPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewCaseRegisterationPanel
     */
    private JPanel newCaseRegisterPanel;
    private Sys sys;
    private HomeScreen homeScreen;
    DatabaseConnection_CaseDetails dbConnCaseDetails;
    PreparedStatement stmt;
    
    public NewCaseRegisterationPanel(JPanel newCaseRegisterPanel,Sys sys,HomeScreen homeScreen) {
        initComponents();
        
        this.newCaseRegisterPanel = newCaseRegisterPanel;
        this.sys = sys;
        this.homeScreen = homeScreen;
        setSize(1040, 544);
        DescriptionTextField.setDocument(new JTextFieldLimit(250));
        clearFields();
        dbConnCaseDetails = new DatabaseConnection_CaseDetails();
    }
    
    public void clearFields(){
        
        //add fields so they can be cleared
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        DateOfOffenceDateChooser = new com.toedter.calendar.JDateChooser();
        DateOfOffenceLabel = new javax.swing.JLabel();
        DescriptionTextField = new javax.swing.JTextField();
        DateOfOffenceLabel1 = new javax.swing.JLabel();
        FIRNumSelect = new javax.swing.JComboBox<>();
        DateOfOffenceLabel2 = new javax.swing.JLabel();
        GenerateCrimeIDTextField = new javax.swing.JTextField();
        SubmitDetailsButton = new java.awt.Button();

        setBackground(new java.awt.Color(0, 102, 153));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Register your case below by adding all the details.........");

        DescriptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DescriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        DescriptionLabel.setText("Description (in 250 words):");

        DateOfOffenceDateChooser.setDateFormatString("YYYY-MM-dd");

        DateOfOffenceLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DateOfOffenceLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateOfOffenceLabel.setText("DateOfOffence:");

        DescriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionTextFieldActionPerformed(evt);
            }
        });
        DescriptionTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DescriptionTextFieldKeyPressed(evt);
            }
        });

        DateOfOffenceLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DateOfOffenceLabel1.setForeground(new java.awt.Color(255, 255, 255));
        DateOfOffenceLabel1.setText("Select FIR Number:");

        DateOfOffenceLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DateOfOffenceLabel2.setForeground(new java.awt.Color(255, 255, 255));
        DateOfOffenceLabel2.setText("Generate Crime ID:");

        GenerateCrimeIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateCrimeIDTextFieldActionPerformed(evt);
            }
        });
        GenerateCrimeIDTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GenerateCrimeIDTextFieldKeyPressed(evt);
            }
        });

        SubmitDetailsButton.setLabel("Submit Details");
        SubmitDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitDetailsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DateOfOffenceLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GenerateCrimeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DateOfOffenceLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FIRNumSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DateOfOffenceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateOfOffenceDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DescriptionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(SubmitDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titleLabel)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DateOfOffenceDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateOfOffenceLabel))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescriptionLabel)
                    .addComponent(DescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateOfOffenceLabel1)
                    .addComponent(FIRNumSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateOfOffenceLabel2)
                    .addComponent(GenerateCrimeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(SubmitDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DescriptionTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DescriptionTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionTextFieldKeyPressed

    private void DescriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionTextFieldActionPerformed

    private void GenerateCrimeIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateCrimeIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerateCrimeIDTextFieldActionPerformed

    private void GenerateCrimeIDTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GenerateCrimeIDTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerateCrimeIDTextFieldKeyPressed

    private void SubmitDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitDetailsButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            dbConnCaseDetails.databaseConnectionCaseDetails();
//            java.util.Date date = new java.util.Date();
            String sqlQueryStoreData = "insert into casedetails(dateOfOffence, descr, firNum) values(?,?,?)";
            stmt = dbConnCaseDetails.con.prepareStatement(sqlQueryStoreData);
            
//            SimpleDateFormat Date_Format = new SimpleDateFormat("dd-MM-yyyy"); 
            java.util.Date utilDate=(java.util.Date) DateOfOffenceDateChooser.getDate();
            java.sql.Date  sqlDate=new java.sql.Date(utilDate.getDate());

//            Date_Format.format(DateOfOffenceDateChooser.getDate());
            
            stmt.setDate(1, new java.sql.Date(sqlDate.getDate()));
            stmt.setString(2, DescriptionTextField.getText());
            stmt.setInt(3, 123);
            
            stmt.executeUpdate();
            stmt.close();
            dbConnCaseDetails.closeConnectionCaseDetails();
            
            //open once again to get crime id
            //get crime id - hard coded 
            dbConnCaseDetails.databaseConnectionCaseDetails();
            int crimeId = dbConnCaseDetails.getCrimeId(123);
            GenerateCrimeIDTextField.setText(String.valueOf(crimeId));
            dbConnCaseDetails.closeConnectionCaseDetails();
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SubmitDetailsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateOfOffenceDateChooser;
    private javax.swing.JLabel DateOfOffenceLabel;
    private javax.swing.JLabel DateOfOffenceLabel1;
    private javax.swing.JLabel DateOfOffenceLabel2;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JTextField DescriptionTextField;
    private javax.swing.JComboBox<String> FIRNumSelect;
    private javax.swing.JTextField GenerateCrimeIDTextField;
    private java.awt.Button SubmitDetailsButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
