/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package crime_branch_enterprise.model;


import java.sql.PreparedStatement;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import model.JTextFieldLimit;
import model.Sys;
import ui.HomeScreen;
import ui.MainJFrame;
import crime_branch_enterprise.model.FIR;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.event.PopupMenuEvent;
import javax.swing.event.PopupMenuListener;
import ui.HomePanel;
//import utility

/**
 *
 * @author hindupurv
 */
public class NewCaseRegisterationPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewCaseRegisterationPanel
     */
    private JPanel newCaseRegisterPanel;
    private Sys sys;
    private HomeScreen homeScreen;
    DatabaseConnection_CaseDetails dbConnCaseDetails;
    PreparedStatement stmt;
    MainJFrame mainObj = new MainJFrame();
    HomePanel homePanel;
    Random rand;
    int crimeId;
    
    FIRDirectory fIRDirectory;
    List<Integer> listOfFIRNumbers = new ArrayList<>();
        
    
    
    public NewCaseRegisterationPanel(JPanel newCaseRegisterPanel,Sys sys,HomeScreen homeScreen, HomePanel homePanel) {
        initComponents();
        
        this.newCaseRegisterPanel = newCaseRegisterPanel;
        this.sys = sys;
        this.homeScreen = homeScreen;
        setSize(1040, 544);
        PhoneNumberTextField.setDocument(new JTextFieldLimit(10));
        EmailIdTextField.setDocument(new JTextFieldLimit(50));
        clearFields();
        dbConnCaseDetails = new DatabaseConnection_CaseDetails();
        this.homePanel = homePanel;
        
        rand = new Random();
        // Generate random integers in range 0 to 999
        crimeId = rand.nextInt(1000);        
    }
    
    
    
    public void clearFields(){
        
        //add fields so they can be cleared
        
    }
   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        DateOfOffenceLabel1 = new javax.swing.JLabel();
        FIRNumSelect = new javax.swing.JComboBox<>();
        DateOfOffenceLabel2 = new javax.swing.JLabel();
        GenerateCrimeIDTextField = new javax.swing.JTextField();
        SubmitDetailsButton = new java.awt.Button();
        EmailIdLabel = new javax.swing.JLabel();
        EmailIdTextField = new javax.swing.JTextField();
        PhoneNumberLabel = new javax.swing.JLabel();
        PhoneNumberTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 102, 153));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Register your case below by adding all the details.........");

        DateOfOffenceLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DateOfOffenceLabel1.setForeground(new java.awt.Color(255, 255, 255));
        DateOfOffenceLabel1.setText("Select FIR Number:");

        FIRNumSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FIRNumSelectMouseClicked(evt);
            }
        });
        FIRNumSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIRNumSelectActionPerformed(evt);
            }
        });

        DateOfOffenceLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DateOfOffenceLabel2.setForeground(new java.awt.Color(255, 255, 255));
        DateOfOffenceLabel2.setText("Generate Crime ID:");

        GenerateCrimeIDTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GenerateCrimeIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateCrimeIDTextFieldActionPerformed(evt);
            }
        });
        GenerateCrimeIDTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GenerateCrimeIDTextFieldKeyPressed(evt);
            }
        });

        SubmitDetailsButton.setLabel("Submit Details");
        SubmitDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitDetailsButtonActionPerformed(evt);
            }
        });

        EmailIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EmailIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailIdLabel.setText("Email Id:");

        EmailIdTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        PhoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PhoneNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNumberLabel.setText("Phone Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DateOfOffenceLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PhoneNumberLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FIRNumSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(DateOfOffenceLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(GenerateCrimeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EmailIdLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(SubmitDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titleLabel)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateOfOffenceLabel1)
                    .addComponent(FIRNumSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailIdLabel))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberLabel)
                    .addComponent(PhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateOfOffenceLabel2)
                    .addComponent(GenerateCrimeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(SubmitDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateCrimeIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateCrimeIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerateCrimeIDTextFieldActionPerformed

    private void GenerateCrimeIDTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GenerateCrimeIDTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerateCrimeIDTextFieldKeyPressed

    private void SubmitDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitDetailsButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            dbConnCaseDetails.databaseConnectionCaseDetails();
            
            String sqlQueryStoreData = "insert into casedetails(crimeId, firNum, emailId, phoneNum) values(?,?,?,?)";
            stmt = dbConnCaseDetails.con.prepareStatement(sqlQueryStoreData);
            String emailId = EmailIdTextField.getText();
            int phoneNumber = 0;
            try
            {
                phoneNumber = Integer.parseInt(PhoneNumberTextField.getText());
            }
            catch(NumberFormatException ex){ }
            
            String valueFIRID = FIRNumSelect.getSelectedItem().toString();
            
            
            stmt.setInt(1, crimeId);
            stmt.setString(2, valueFIRID);
            stmt.setString(3, emailId);
            stmt.setInt(4, phoneNumber);
            
            stmt.executeUpdate();
            stmt.close();
            dbConnCaseDetails.closeConnectionCaseDetails();
            
            //open once again to get crime id
            //get crime id - hard coded 
            dbConnCaseDetails.databaseConnectionCaseDetails();
            int crimeId = dbConnCaseDetails.getCrimeId(Integer.parseInt(valueFIRID));
            GenerateCrimeIDTextField.setText(String.valueOf(crimeId));
            dbConnCaseDetails.closeConnectionCaseDetails();
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SubmitDetailsButtonActionPerformed

    private void FIRNumSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIRNumSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIRNumSelectActionPerformed

    private void FIRNumSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FIRNumSelectMouseClicked
        // TODO add your handling code here:
        //get List of firs as select dropdown
        System.out.println("FIRNumSelectMouseClicked");
        
        fIRDirectory = new FIRDirectory();
        FIRNumSelect = new JComboBox();
        for(int i=0; i<fIRDirectory.firList.size();i++)
        {
            System.out.println(fIRDirectory.firList.get(0).getFirId());
        }
        for(FIR fir: fIRDirectory.firList)
        {
            System.out.println("firdir: "+fir.getFirId());
            listOfFIRNumbers.add(fir.getFirId());
        }
        for(Integer firIdNum :  listOfFIRNumbers)
        {
            System.out.println("firnum: "+firIdNum);
            FIRNumSelect.addItem(String.valueOf(firIdNum));
        }
    }//GEN-LAST:event_FIRNumSelectMouseClicked
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateOfOffenceLabel1;
    private javax.swing.JLabel DateOfOffenceLabel2;
    private javax.swing.JLabel EmailIdLabel;
    private javax.swing.JTextField EmailIdTextField;
    private javax.swing.JComboBox<String> FIRNumSelect;
    private javax.swing.JTextField GenerateCrimeIDTextField;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JTextField PhoneNumberTextField;
    private java.awt.Button SubmitDetailsButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
