/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package crime_branch_enterprise.model;

import java.awt.CardLayout;
import java.sql.PreparedStatement;
import javax.swing.JPanel;
import model.Sys;
import ui.HomePanel;
import ui.HomeScreen;

/**
 *
 * @author ASUS
 */
public class NewFIRRegister extends javax.swing.JPanel {

    /**
     * Creates new form NewFIRRegister
     */
    
    private JPanel newFIRRegisterPanel;
    private Sys sys;
    private HomeScreen homeScreen;
    DatabaseConnection_FirDetails dbConnFIRDetails;
    PreparedStatement stmt;
   

    public NewFIRRegister(JPanel newFIRRegisterPanel,Sys sys,HomeScreen homeScreen) {
        initComponents();
        
        this.newFIRRegisterPanel = newFIRRegisterPanel;
        this.sys = sys;
        this.homeScreen = homeScreen;
        setSize(1040, 544);
        
        dbConnFIRDetails = new DatabaseConnection_FirDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
