/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package crime_branch_enterprise.model;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Sys;
import ui.HomeScreen;


/**
 *
 * @author Sal <your.name at your.org>
 */
public class ReadCaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReadCaseJPanel
     */
    private JPanel readCase;
    private Sys sys;
    private HomeScreen homeScreen;
    
    NewCaseRegisterDirectory registerDir;
    DatabaseConnection_CaseDetails dbConCaseDetails = new DatabaseConnection_CaseDetails();
    OfficerDirectory officerDir;
    
    DatabaseConnection_person dbConPersonDetails;
    
    
    public ReadCaseJPanel(NewCaseRegisterDirectory registerDir, OfficerDirectory officerDir, DatabaseConnection_person dbConPersonDetails) {
        initComponents();
        
        this.registerDir = registerDir;
        this.officerDir = officerDir;
        
        this.dbConPersonDetails = dbConPersonDetails;
    }
    
    public ReadCaseJPanel ( JPanel readCase, Sys sys, HomeScreen homeScreen) 
    {    
        initComponents();
        this.readCase = readCase;
        this.sys = sys;
        this.homeScreen = homeScreen;

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeadingLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CaseDirectoryTable = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        DescriptionLabel = new javax.swing.JLabel();
        DateOfReportLabel = new javax.swing.JLabel();
        datefieldRead = new javax.swing.JTextField();
        SelectFIRNumberLabel = new javax.swing.JLabel();
        EmailIdLabel = new javax.swing.JLabel();
        EmailIdTextField = new javax.swing.JTextField();
        DateOfReportDateChooser = new com.toedter.calendar.JDateChooser();
        SelectOfficer = new javax.swing.JComboBox<>();
        PhoneNumberTextField1 = new javax.swing.JTextField();
        btnCrime = new javax.swing.JButton();
        txtgetFP = new javax.swing.JTextField();
        txtCriminal = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 0, 0));

        HeadingLabel.setBackground(new java.awt.Color(153, 0, 0));
        HeadingLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        HeadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        HeadingLabel.setText("CASE DIRECTORY");

        CaseDirectoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "EMAIL ID", "DATE OF REPORT", "PHONE NUMBER", "SELECTED OFFICER"
            }
        ));
        jScrollPane1.setViewportView(CaseDirectoryTable);

        updateBtn.setBackground(new java.awt.Color(102, 0, 0));
        updateBtn.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(102, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        viewBtn.setBackground(new java.awt.Color(102, 0, 0));
        viewBtn.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        viewBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewBtn.setText("VIEW");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        DescriptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DescriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        DescriptionLabel.setText("Phone Number:");

        DateOfReportLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DateOfReportLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateOfReportLabel.setText("Date Of Report:");

        datefieldRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datefieldReadActionPerformed(evt);
            }
        });
        datefieldRead.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                datefieldReadKeyPressed(evt);
            }
        });

        SelectFIRNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SelectFIRNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        SelectFIRNumberLabel.setText("Select Officer:");

        EmailIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EmailIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailIdLabel.setText("Email Id:");

        EmailIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailIdTextFieldActionPerformed(evt);
            }
        });
        EmailIdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmailIdTextFieldKeyPressed(evt);
            }
        });

        DateOfReportDateChooser.setDateFormatString("YYYY-MM-dd");

        SelectOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectOfficerActionPerformed(evt);
            }
        });

        PhoneNumberTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberTextField1ActionPerformed(evt);
            }
        });
        PhoneNumberTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PhoneNumberTextField1KeyPressed(evt);
            }
        });

        btnCrime.setBackground(new java.awt.Color(102, 0, 0));
        btnCrime.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        btnCrime.setForeground(new java.awt.Color(255, 255, 255));
        btnCrime.setText("Find Criminal");
        btnCrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrimeActionPerformed(evt);
            }
        });

        txtgetFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgetFPActionPerformed(evt);
            }
        });

        txtCriminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCriminalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCriminal, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SelectFIRNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SelectOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DateOfReportLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DateOfReportDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(datefieldRead, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(DescriptionLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtgetFP))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EmailIdLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EmailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(194, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(293, 293, 293)
                    .addComponent(HeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(336, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(289, 289, 289)
                    .addComponent(PhoneNumberTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(479, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateOfReportLabel)
                            .addComponent(DateOfReportDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datefieldRead, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(DescriptionLabel))
                    .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(EmailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1))
                        .addComponent(EmailIdLabel))
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SelectFIRNumberLabel)
                        .addComponent(SelectOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgetFP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtCriminal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(732, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(336, 336, 336)
                    .addComponent(PhoneNumberTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(426, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed

            java.sql.Date sqlDate = null;
            String  DateOfOffence ="";
            boolean flag=false;
            int selectedRowIndex = CaseDirectoryTable.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a row to update");
                return;
            }
            DefaultTableModel model = (DefaultTableModel) CaseDirectoryTable.getModel();
            NewCaseRegister newCaseRegister = (NewCaseRegister) model.getValueAt(selectedRowIndex,0);
            
            String dateOfReport = DateOfReportDateChooser.getDate().toString();
            String phoneNum = datefieldRead.getText();
            String emailId =EmailIdTextField.getText();
            String selectedOfficer = SelectOfficer.getSelectedItem().toString();

            JOptionPane.showMessageDialog(this, "Case Information Updated");
            
            newCaseRegister.setPhoneNum(phoneNum);
//            newCaseRegister.setEmailId(emailId);
            newCaseRegister.setOfficerName(selectedOfficer);

            populateTable();
            
            NewCaseRegister newCaseRegister1= new NewCaseRegister(emailId,phoneNum,dateOfReport,selectedOfficer);
            
            
            //db update
            dbConCaseDetails.updateCaseDataToDB(newCaseRegister1);
            
//            DateOfReportDateChooser.set
            datefieldRead.setText("");
            EmailIdTextField.setText("");
//            SelectedOfficer
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = CaseDirectoryTable.getSelectedRow();

        if(selectedRowIndex <0){
            JOptionPane.showMessageDialog(this, "Please enter the row you want to delete");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) CaseDirectoryTable.getModel();
        NewCaseRegister newCaseRegister = (NewCaseRegister) model.getValueAt(selectedRowIndex,0);

        NewCaseRegisterDirectory.newCaseRegisterList.remove(newCaseRegister);
        
        dbConCaseDetails.deleteNewCaseDataInDB(newCaseRegister);

        JOptionPane.showMessageDialog(this, "Requested Record is Deleted");
        populateTable();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = CaseDirectoryTable.getSelectedRow();
        if(selectedRowIndex <0){
            JOptionPane.showMessageDialog(this, "Please enter the row you want to view");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) CaseDirectoryTable.getModel();
        NewCaseRegister newCaseRegister = (NewCaseRegister) model.getValueAt(selectedRowIndex,0);
        

        //add data to NewCaseRegister
//        DateOfReportDateChooser.setDate(newCaseRegister.getDateOfReport());
        datefieldRead.setText(String.valueOf(newCaseRegister.getPhoneNum()));
        EmailIdTextField.setText(String.valueOf(newCaseRegister.getEmailId()));
        SelectOfficer.setSelectedItem(newCaseRegister.getOfficerName());
        
        //disable email id so it cannot be updated
        EmailIdTextField.setEnabled(false);
        
    }//GEN-LAST:event_viewBtnActionPerformed

    private void datefieldReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datefieldReadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datefieldReadActionPerformed

    private void datefieldReadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datefieldReadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_datefieldReadKeyPressed

    private void EmailIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailIdTextFieldActionPerformed

    private void EmailIdTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailIdTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailIdTextFieldKeyPressed

    private void SelectOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectOfficerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectOfficerActionPerformed

    private void PhoneNumberTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberTextField1ActionPerformed

    private void PhoneNumberTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhoneNumberTextField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberTextField1KeyPressed

    private void btnCrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrimeActionPerformed
        // TODO add your handling code here:

         int fp = Integer.parseInt(txtgetFP.getText());
       //dbConPersonDetails = new DatabaseConnection_person();
       String getCriminalName = dbConPersonDetails.matchFingerPrintDataToDB(fp);
        txtCriminal.setText(getCriminalName);
    }//GEN-LAST:event_btnCrimeActionPerformed

    private void txtgetFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgetFPActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtgetFPActionPerformed

    private void txtCriminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCriminalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCriminalActionPerformed

    private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) CaseDirectoryTable.getModel();
        model.setRowCount(0);

        for (NewCaseRegister newCase : registerDir.getNewCaseRegisterList()) {

            Object[] row = new Object[7];
            row[0] = newCase;
            row[1] = newCase.getDateOfReport();
            row[2] = newCase.getPhoneNum();
            //row[3] = newCase.getEmailId();
            row[3] = newCase.getOfficerName();

            model.addRow(row);

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CaseDirectoryTable;
    private com.toedter.calendar.JDateChooser DateOfReportDateChooser;
    private javax.swing.JLabel DateOfReportLabel;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JLabel EmailIdLabel;
    private javax.swing.JTextField EmailIdTextField;
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JTextField PhoneNumberTextField1;
    private javax.swing.JLabel SelectFIRNumberLabel;
    private javax.swing.JComboBox<String> SelectOfficer;
    private javax.swing.JButton btnCrime;
    private javax.swing.JTextField datefieldRead;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCriminal;
    private javax.swing.JTextField txtgetFP;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
