/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ResourceModel;

import ui.*;

import javax.swing.JOptionPane;

public class CreateWeapon extends javax.swing.JPanel {

    WeaponDirectory weaponHistory;
    DatabaseConnection_weapon dbConWeaponDetails;
    
    public CreateWeapon(WeaponDirectory weaponHistory) {
        initComponents();
        this.weaponHistory = weaponHistory;
        dbConWeaponDetails = new DatabaseConnection_weapon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbWeaponId = new javax.swing.JLabel();
        txtWeaponId = new javax.swing.JTextField();
        lbWeaponType = new javax.swing.JLabel();
        txtWeaponType = new javax.swing.JTextField();
        lbCount = new javax.swing.JLabel();
        txtCount = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 0, 0));

        lbTitle.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Weapon Form");

        lbWeaponId.setForeground(new java.awt.Color(255, 255, 255));
        lbWeaponId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWeaponId.setText("Weapon Id");

        lbWeaponType.setForeground(new java.awt.Color(255, 255, 255));
        lbWeaponType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWeaponType.setText("Weapon Type");

        txtWeaponType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeaponTypeActionPerformed(evt);
            }
        });

        lbCount.setForeground(new java.awt.Color(255, 255, 255));
        lbCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCount.setText("Count");

        txtCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(204, 204, 204));
        btnAdd.setText("Add Weapon");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbWeaponId, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(lbWeaponType, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(lbCount, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWeaponId, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtWeaponType)
                            .addComponent(txtCount)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(474, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWeaponId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbWeaponId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWeaponType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbWeaponType, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCount, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnAdd)
                .addContainerGap(239, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        boolean isValid = Validation();
            if (isValid) {
        int weaponId = Integer.parseInt(txtWeaponId.getText());
        String weaponName = txtWeaponType.getText();
        int wcount = Integer.parseInt(txtCount.getText());      

        Weapon w = weaponHistory.addNewWeapon();

        w.setWeaponId(weaponId);
        w.setwType(weaponName);
        w.setWCount(wcount);
        
        dbConWeaponDetails.addWeaponDataToDB(w);
        JOptionPane.showMessageDialog(this, "New Weapon is added.");

        txtWeaponId.setText("");
        txtWeaponType.setText("");
        txtCount.setText("");
            }   
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtWeaponTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeaponTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeaponTypeActionPerformed

    private void txtCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel lbCount;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbWeaponId;
    private javax.swing.JLabel lbWeaponType;
    private javax.swing.JTextField txtCount;
    private javax.swing.JTextField txtWeaponId;
    private javax.swing.JTextField txtWeaponType;
    // End of variables declaration//GEN-END:variables
 private boolean Validation() {
    if (txtWeaponId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Weapon ID");
            return false;
        } 
                
        try {
        Integer.parseInt(txtWeaponId.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a numerical value for Weapon ID");
            
        }
        
        if (txtWeaponType.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Weapon Type");
            return false;
        } else {
            if (!(txtWeaponType.getText().matches("[a-zA-Z]*"))) {
                JOptionPane.showMessageDialog(this, "Please enter Valid Weapon Type");
                return false;
            }
        }
        
        if (txtCount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Weapon count");
            return false;
        } 
                
        try {
        Integer.parseInt(txtCount.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a numerical value for Weapon count");
            
        }
       
        return true;
        
    }
}
