/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ResourceModel;
import ForensicsModel.*;
import NewsModel.*;
import NewsModel.NewsHistory;
import NewsModel.NewspaperHistory;
import NewsModel.AuthorHistory;
import NewsModel.PublicationHistory;
import NewsModel.ReporterHistory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Sys;
import ui.HomeScreen;
import ui.LoginScreen;

/**
 *
 * @author Sal <your.name at your.org>
 */
public class ResourceMainJPanel extends javax.swing.JPanel {
    Army army;
    Weapon weapon;
    TrainedAnimal tAnimal;
    Government gov;
    Prison prison;
    Jail jail;
    ArmyDirectory armyHistory;
    WeaponDirectory weaponHistory;
    TrainedAnimalDirectory animalHistory;
    GovDirectory govHistory;
    PrisonDirectory prisonHistory;
    JailDirectory jailHistory;
    /**
     * Creates new form NewsMainJPanel
     */
    
    JPanel resourceAdminJPanel;
    Sys sys;
    HomeScreen homeScreen;
    
    public ResourceMainJPanel(JPanel resourceAdminJPanel,Sys sys,HomeScreen homeScreen) 
    {
        initComponents();
        
        this.resourceAdminJPanel = resourceAdminJPanel;
        this.sys = sys;
        this.homeScreen = homeScreen;
        setSize(1040, 544);
    }
    
    public ResourceMainJPanel() {
//        initComponents();
        this.army = new Army();
        this.weapon = new Weapon();
        this.tAnimal = new TrainedAnimal();
        this.gov = new Government();
        this.prison = new Prison(); 
        this.jail = new Jail();
        this.armyHistory = new ArmyDirectory();
        this.weaponHistory = new WeaponDirectory();
        this.animalHistory = new TrainedAnimalDirectory();
        this.govHistory = new GovDirectory();
        this.prisonHistory = new PrisonDirectory(); 
        this.jailHistory = new JailDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJSplitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        tAnimalBtn = new javax.swing.JButton();
        weaponBtn = new javax.swing.JButton();
        govBtn = new javax.swing.JButton();
        prisonBtn = new javax.swing.JButton();
        armyBtn = new javax.swing.JButton();
        jailBtn = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        controlPanel.setBackground(new java.awt.Color(102, 0, 0));

        tAnimalBtn.setBackground(new java.awt.Color(102, 0, 0));
        tAnimalBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        tAnimalBtn.setForeground(new java.awt.Color(255, 255, 255));
        tAnimalBtn.setText("TRAINED ANIMAL");
        tAnimalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAnimalBtnActionPerformed(evt);
            }
        });

        weaponBtn.setBackground(new java.awt.Color(102, 0, 0));
        weaponBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        weaponBtn.setForeground(new java.awt.Color(255, 255, 255));
        weaponBtn.setText("WEAPON");
        weaponBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weaponBtnActionPerformed(evt);
            }
        });

        govBtn.setBackground(new java.awt.Color(102, 0, 0));
        govBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        govBtn.setForeground(new java.awt.Color(255, 255, 255));
        govBtn.setText("GOVERNMENT");
        govBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                govBtnActionPerformed(evt);
            }
        });

        prisonBtn.setBackground(new java.awt.Color(102, 0, 0));
        prisonBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        prisonBtn.setForeground(new java.awt.Color(255, 255, 255));
        prisonBtn.setText("PRISON");
        prisonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prisonBtnActionPerformed(evt);
            }
        });

        armyBtn.setBackground(new java.awt.Color(102, 0, 0));
        armyBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        armyBtn.setForeground(new java.awt.Color(255, 255, 255));
        armyBtn.setText("ARMY");
        armyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                armyBtnActionPerformed(evt);
            }
        });

        jailBtn.setBackground(new java.awt.Color(102, 0, 0));
        jailBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jailBtn.setForeground(new java.awt.Color(255, 255, 255));
        jailBtn.setText("JAIL");
        jailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jailBtnActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(102, 0, 0));
        btnLogOut.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("LOG OUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weaponBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tAnimalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(armyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(govBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prisonBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jailBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(20, 20, 20))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(armyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tAnimalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(weaponBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(govBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prisonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnLogOut)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        mainJSplitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        mainJSplitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJSplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tAnimalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAnimalBtnActionPerformed
        // TODO add your handling code here:
        TAnimalViewJPanel animalPanel = new TAnimalViewJPanel(animalHistory);
        mainJSplitPane.setRightComponent(animalPanel);
    }//GEN-LAST:event_tAnimalBtnActionPerformed

    private void weaponBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weaponBtnActionPerformed
        // TODO add your handling code here:
        WeaponViewJPanel weaponPanel = new WeaponViewJPanel(weaponHistory);
        mainJSplitPane.setRightComponent(weaponPanel);
    }//GEN-LAST:event_weaponBtnActionPerformed

    private void govBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_govBtnActionPerformed
        // TODO add your handling code here:
        GovViewJPanel govPanel = new GovViewJPanel(govHistory);
        mainJSplitPane.setRightComponent(govPanel);
    }//GEN-LAST:event_govBtnActionPerformed

    private void prisonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prisonBtnActionPerformed
        // TODO add your handling code here:
        PrisonViewJPanel prisonPanel = new PrisonViewJPanel(prisonHistory);
        mainJSplitPane.setRightComponent(prisonPanel);
    }//GEN-LAST:event_prisonBtnActionPerformed

    private void armyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_armyBtnActionPerformed
        // TODO add your handling code here:
        ArmyViewJPanel armyPanel = new ArmyViewJPanel(armyHistory);
        mainJSplitPane.setRightComponent(armyPanel);
    }//GEN-LAST:event_armyBtnActionPerformed

    private void jailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jailBtnActionPerformed
        // TODO add your handling code here:
        JailViewJPanel jailPanel = new JailViewJPanel(jailHistory);
        mainJSplitPane.setRightComponent(jailPanel);
    }//GEN-LAST:event_jailBtnActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
         JPanel selectedPanel = new LoginScreen(resourceAdminJPanel,sys, homeScreen);

        resourceAdminJPanel.add("WorkAreaJPanel",selectedPanel);
        CardLayout layout = (CardLayout) resourceAdminJPanel.getLayout();
        layout.next(resourceAdminJPanel);
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton armyBtn;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton govBtn;
    private javax.swing.JButton jailBtn;
    private javax.swing.JSplitPane mainJSplitPane;
    private javax.swing.JButton prisonBtn;
    private javax.swing.JButton tAnimalBtn;
    private javax.swing.JButton weaponBtn;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
